---
# tasks file for upload-public-key

- name: Upload public key to AWS
  ec2_key:
    name: "{{ aws_key_name }}"
    key_material: "{{ lookup('file', '/home/ec2-user/.ssh/{{ app_name }}.pub') }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"

