---
# tasks file for create-security-group
#
- name: create aws security group
  ec2_group:
    name: "{{ security_group_name }}"
    description: "{{ security_group_name }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port
      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on http port        
  register: result_security_group 
