---
# tasks file for create-ec2
- name: Provision instance(s)
  ec2: 
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    key_name: "{{ aws_key_name }}"
    group_id: "{{ result_security_group.group_id }}"
    image: "{{ ec2_image }}"
    instance_type: t2.micro
    region: "{{ aws_region }}"
    wait: true
    count: 1
    instance_tags:
      Name: "{{ app_name }}"
  register: ec2
  
- name: Print ec2
  debug:
    var: ec2.instances[0].private_ip

- name: Add new instance to host group
  add_host:
    hostname: "{{ ec2.instances[0].private_ip }}"
    groupname: launched
    ansible_ssh_private_key_file: "{{ role_path }}/files/demoapp"

- name: Wait for ssh to come up
  wait_for: port=22 delay=60 timeout=320
  with_items: ec2.instances
